#Create Order
POST http://localhost:3000/orders/createOrder HTTP/1.1
content-type: application/json

{
  "user": {
    "email": "TestEmail14@web.de"
  },
  "storeId": "5f31406deae5b044240a57c8",
  "date": "date",
  // type: "pickUp",
  // status: { overall: "inProcess", orderReceived: 1, packageReady: 0, packagePickUp: 0 },
  "type": "delivery",
  "status": {
    "finished": false,
    "successfully": false,
    "steps": {
      "orderReceived": 1,
      "paymentReceived": 0,
      "inDelivery": 0
    }
  },
  "shippingAddress": "address",
  "billingAddress": "address",
  "products": [
      [{
          "storeId": "5f31406deae5b044240a57c8",
          "productId": "10",
          "stockAmount": 1
      },1],
      [{
          "storeId": "5f31406deae5b044240a57c8",
          "productId": "12",
          "stockAmount": 1
      },3]
  ],
  "payment": "paypal",
  "totalSum": 100,
  "currency": "EUR",
  "currencySymbol": "€"
}
###

#Get Stores Orders
GET http://localhost:3000/orders/stores-orders/6042541d40aa5c7b38dc3807 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDI1NDFiNDBhYTVjN2IzOGRjMzgwNiIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTYyNzY2OTAsImV4cCI6MTYxNjg4MTQ5MH0.RHPWtbCYUjvnmbfgn3J17Ff-IQEz_ZSX7FSkYgcz2KI
###

#Get Users Orders
GET http://localhost:3000/orders/users-orders HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDI1NDFiNDBhYTVjN2IzOGRjMzgwNiIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTY2MjI2MTYsImV4cCI6MTYxNzIyNzQxNn0.ZgMw2GYgghdLSXIFasbvPtdeX6H0YftTLihVEsfQpl8
###

#Get Users Orders
GET http://localhost:3000/orders HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDI1NDFiNDBhYTVjN2IzOGRjMzgwNiIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTYyNzY2OTAsImV4cCI6MTYxNjg4MTQ5MH0.RHPWtbCYUjvnmbfgn3J17Ff-IQEz_ZSX7FSkYgcz2KI
###

#Search Stores Orders
GET http://localhost:3000/orders/search-store-order?search=Test HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNDI1NDFhNDBhYTVjN2IzOGRjMzgwMiIsImVtYWlsIjoiVGVzdEVtYWlsMUB3ZWIuZGUiLCJpYXQiOjE2MTc5OTU5MzgsImV4cCI6MTYxODYwMDczOH0.nYjHjhiyqW44QTrdKijZXCqdBZCFjjfSAMJSx0H75NI
###