#Get Paypal Access Token
POST https://api-m.sandbox.paypal.com/v1/oauth2/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json
Accept-Language: en_US
Authorization: Basic AZ4Ot1_cYotHmBv5ljIROuwrazfyUOkvSR2hDVfCrAaB1wTpkkaTzi9C7dIp08HTX6lEVMdOZ4l4FZrc ED1zXLfeM9qL7AFxpN8jhm-ow51xA0iQFgQmKrxa9a7is4PlwztEDQBls5_bc2cA-oaGkIlcWo30pnUM

grant_type=client_credentials
###

#Create Paypal Signup Link
POST https://api-m.sandbox.paypal.com/v2/customer/partner-referrals HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAK6erHfhdYtqz80fjZIsgiVFrqSMrVLBCtkzC1079NPD4EJninDftWb0Q_-rDoKoLHvKblvbMI1FrWo3Jm59kK6o3T0sg

{
    "tracking_id": "<Tracking-ID>",
    "operations": [
      {
        "operation": "API_INTEGRATION",
        "api_integration_preference": {
          "rest_api_integration": {
            "integration_method": "PAYPAL",
            "integration_type": "THIRD_PARTY",
            "third_party_details": {
              "features": [
                "PAYMENT",
                "REFUND"
             ]
            }
          }
        }
      }
    ],
    "products": [
      "EXPRESS_CHECKOUT"
    ],
    "legal_consents": [
      {
        "type": "SHARE_DATA_CONSENT",
        "granted": true
      }
    ],
    "partner_config_override/return_url": ""
}
###

# Retrieve Merchant Id (= id of registered store)
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations?tracking_id=6042541d40aa5c7b38dc3807 HTTP/1.1
content-type: application/json
Authorization: Bearer A21AALQTrE0qtO1eMDwyJNxkm-rzJBIXs8UpYNvR1cqTqZaapqycyope2K3HfQOJ3VnMLoE9SIyhw4I9XtAsIuD8AJkXS42SQ
###

# Check Onboarding Status
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations/5FHJ5NA2X94VG HTTP/1.1
content-type: application/json
Authorization: Bearer A21AALQTrE0qtO1eMDwyJNxkm-rzJBIXs8UpYNvR1cqTqZaapqycyope2K3HfQOJ3VnMLoE9SIyhw4I9XtAsIuD8AJkXS42SQ
###

#Create Order
POST https://api-m.sandbox.paypal.com/v2/checkout/orders HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAK6erHfhdYtqz80fjZIsgiVFrqSMrVLBCtkzC1079NPD4EJninDftWb0Q_-rDoKoLHvKblvbMI1FrWo3Jm59kK6o3T0sg

{
  "intent": "CAPTURE",
  "purchase_units": [{
    "amount": {
        "currency_code": "USD",
        "value": "100.00"
    },
    "payee": {
        "email_address": "sb-wqpm05264764@business.example.com"
    },
    "payment_instruction": {
      "disbursement_mode": "INSTANT",
      "platform_fees": [{
          "amount": {
              "currency_code": "USD",
              "value": "25.00"
          }
      }]
    }
  }]
}
###

# Capture Order (like approve order)
POST https://api-m.sandbox.paypal.com/v2/checkout/orders/9BG37138X9185330J/capture HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAK6erHfhdYtqz80fjZIsgiVFrqSMrVLBCtkzC1079NPD4EJninDftWb0Q_-rDoKoLHvKblvbMI1FrWo3Jm59kK6o3T0sg

{}
### 

# Create Paypal SIgnup Link
POST http://localhost:3000/paypal/signup-link HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjU5M2JlMWJkYTJkNzk1YzhhMGNhOSIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTQ3OTA5NjcsImV4cCI6MTYxNTM5NTc2N30.l984HwwxVldvuQdkDhZrb2yiaSeWcsmoT8Fr1S1F-7w

{
  "returnUrl": "/",
  "trackingId": "12345"
}
###

# Create Paypal Order
POST http://localhost:3000/paypal/create-order HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjU5M2JlMWJkYTJkNzk1YzhhMGNhOSIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTQ3OTA5NjcsImV4cCI6MTYxNTM5NTc2N30.l984HwwxVldvuQdkDhZrb2yiaSeWcsmoT8Fr1S1F-7w

# Falsch: dieser call wird dann erst vom server geschickt
{
 "intent": "CAPTURE",
 "purchase_units": [{
   "amount": {
     "currency_code": "USD",
     "value": "100.00"
   },
   "payee": {
     "email_address": "seller@example.com"
   },
   "payment_instruction": {
     "disbursement_mode": "INSTANT",
     "platform_fees": [{
       "amount": {
         "currency_code": "USD",
         "value": "25.00"
       }
     }]
   }
 }]
}
###

# Capture Paypal Order
POST http://localhost:3000/paypal/capture-order HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMjU5M2JlMWJkYTJkNzk1YzhhMGNhOSIsImVtYWlsIjoiVGVzdEVtYWlsNUB3ZWIuZGUiLCJpYXQiOjE2MTQ3OTA5NjcsImV4cCI6MTYxNTM5NTc2N30.l984HwwxVldvuQdkDhZrb2yiaSeWcsmoT8Fr1S1F-7w

{
}
###