##############################
# PAYPAL ################################################################################################################################
##############################
#Get Paypal Access Token
POST https://api-m.sandbox.paypal.com/v1/oauth2/token HTTP/1.1
content-type: application/x-www-form-urlencoded
Accept: application/json
Accept-Language: en_US
Authorization: Basic AZ4Ot1_cYotHmBv5ljIROuwrazfyUOkvSR2hDVfCrAaB1wTpkkaTzi9C7dIp08HTX6lEVMdOZ4l4FZrc ED1zXLfeM9qL7AFxpN8jhm-ow51xA0iQFgQmKrxa9a7is4PlwztEDQBls5_bc2cA-oaGkIlcWo30pnUM

grant_type=client_credentials
###

#Create Paypal Signup Link
POST https://api-m.sandbox.paypal.com/v2/customer/partner-referrals HTTP/1.1
content-type: application/json
Authorization: Bearer A21AALlvc4WhwKYcFG5WIFjZyE57CYgZWvPmyCMFmM4WJ-CLlDG6nq8pndfTJ9ecc4s1MjsubNym3mn8I8dw2Nca4YAdKUpbQ

{
    "tracking_id": "60a8137fefddc767a87d05fd",
    "operations": [
      {
        "operation": "API_INTEGRATION",
        "api_integration_preference": {
          "rest_api_integration": {
            "integration_method": "PAYPAL",
            "integration_type": "THIRD_PARTY",
            "third_party_details": {
              "features": [
                "PAYMENT",
                "REFUND"
             ]
            }
          }
        }
      }
    ],
    "products": [
      "EXPRESS_CHECKOUT"
    ],
    "legal_consents": [
      {
        "type": "SHARE_DATA_CONSENT",
        "granted": true
      }
    ]
}
### "partner_config_override/return_url": ""

# Retrieve Merchant Id (= id of registered store)
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations?tracking_id=60bb6b1c5722982870c1677c HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAKG55WMgFojQNsh7MkYu8nrO6VOHhNgvleW-NdAVVxZhi7EV1j6FUdh4QoRTqsA3HYNfK8ib5B1fBg08ic2y89mTvm6RQ
###

# Retrieve Merchant Id (= id of registered store)
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations?tracking_id=60bab1a623dd065d88e41a1b HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAJHK5BpuMge-9iO5xkxehubs9nEvb9MVw22rBDOjHKz_epAMxk1TQEE-dkZW6rLX79V6flfvYAX9C5D6s4CvBlx2YvLEQ
###

# Track Seller Onboarding Status
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations/5FHJ5NA2X94VG HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAJrI3cItb32sJc6siN7ZxK89himhR-oktZ1eIg4jWRQ5jW3WFfHPu5axxZRQQMO8ctw0AQfCkFLoyM3MbFzjYIB4nRhVg
###

# Create Order
POST https://api-m.sandbox.paypal.com/v2/checkout/orders HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAK6erHfhdYtqz80fjZIsgiVFrqSMrVLBCtkzC1079NPD4EJninDftWb0Q_-rDoKoLHvKblvbMI1FrWo3Jm59kK6o3T0sg

{
  "intent": "CAPTURE",
  "purchase_units": [{
    "amount": {
        "currency_code": "USD",
        "value": "100.00"
    },
    "payee": {
        "email_address": "sb-wqpm05264764@business.example.com"
    },
    "payment_instruction": {
      "disbursement_mode": "INSTANT",
      "platform_fees": [{
          "amount": {
              "currency_code": "USD",
              "value": "25.00"
          }
      }]
    }
  }]
}
###

# Capture Order (like approve order)
POST https://api-m.sandbox.paypal.com/v2/checkout/orders/9BG37138X9185330J/capture HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAK6erHfhdYtqz80fjZIsgiVFrqSMrVLBCtkzC1079NPD4EJninDftWb0Q_-rDoKoLHvKblvbMI1FrWo3Jm59kK6o3T0sg

{}
### 

# Get Order
GET https://api-m.sandbox.paypal.com/v2/checkout/orders/16L62550EU084643J HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAI4_26bkb9CYisOWrRtYTtzmksbaHWBf-n8Pf2ZWKl4MIutppzqZfAJHQFUXQqxD7aE-hG8t7mcvSBd_5D8BsU6VQx7aQ
### 
 
# Test 1813656795176779552 CAD3FBJY72FE8
GET https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations/ HTTP/1.1
content-type: application/json
Authorization: Bearer A21AAI4_26bkb9CYisOWrRtYTtzmksbaHWBf-n8Pf2ZWKl4MIutppzqZfAJHQFUXQqxD7aE-hG8t7mcvSBd_5D8BsU6VQx7aQ
### 

##############################
# INTERNAL ################################################################################################################################
##############################

# Create Paypal SIgnup Link
POST http://localhost:3000/paypal/signup-link HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI2YWU3NTcyMjk4Mjg3MGMxNjc3YiIsImVtYWlsIjoiVGVzdEVtYWlsMTNAd2ViLmRlIiwiaWF0IjoxNjIyODk1NDU4LCJleHAiOjE2MjM1MDAyNTh9.rmqj3YLxEGsuie5IKajv9CAu7kHjjSl76cp9K3_2a6s

{
  "returnUrl": "/",
  "trackingId": "12345"
}
###

# Create Paypal Order
POST http://localhost:3000/paypal/create-order HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI2YWU3NTcyMjk4Mjg3MGMxNjc3YiIsImVtYWlsIjoiVGVzdEVtYWlsMTNAd2ViLmRlIiwiaWF0IjoxNjIyODk1NDU4LCJleHAiOjE2MjM1MDAyNTh9.rmqj3YLxEGsuie5IKajv9CAu7kHjjSl76cp9K3_2a6s

# Falsch: dieser call wird dann erst vom server geschickt
{
 "intent": "CAPTURE",
 "purchase_units": [{
   "amount": {
     "currency_code": "USD",
     "value": "100.00"
   },
   "payee": {
     "email_address": "seller@example.com"
   },
   "payment_instruction": {
     "disbursement_mode": "INSTANT",
     "platform_fees": [{
       "amount": {
         "currency_code": "USD",
         "value": "25.00"
       }
     }]
   }
 }]
}
###

# Capture Paypal Order
POST http://localhost:3000/paypal/capture-order HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwYmI2YWU3NTcyMjk4Mjg3MGMxNjc3YiIsImVtYWlsIjoiVGVzdEVtYWlsMTNAd2ViLmRlIiwiaWF0IjoxNjIyODk1NDU4LCJleHAiOjE2MjM1MDAyNTh9.rmqj3YLxEGsuie5IKajv9CAu7kHjjSl76cp9K3_2a6s

{
}
###

# Simulate Webhook
POST http://localhost:3000/paypal/onboarding-completed HTTP/1.1
content-type: application/json

{
  "id": "WH-2WR32451HC0233532-67976317FL4543714",
  "create_time": "2016-08-01T21:41:28Z",
  "resource_type": "merchant-onboarding",
  "event_type": "MERCHANT.ONBOARDING.COMPLETED",
  "resource": {
    "partner_client_id": "AdZ3f8z-zIFM6t6Yilxvk3q4Iwx4ITRBjGR07q9wPJWms0z3G4ohajp7LdvpaLCeVLBmp5aVQ717YIw0",
    "links": [
      {
        "href": "https://api-m.sandbox.paypal.com/v1/customer/partners/CAD3FBJY72FE8/merchant-integrations/5FHJ5NA2X94VG",
        "rel": "self",
        "method": "GET",
        "description": "Get the merchant status information of merchants onboarded by this partner"
      }
    ],
    "merchant_id": "ELAMYJUN78D6G"
  },
  "links": []
}
###