
# Get All Stores
GET http://localhost:3000/stores HTTP/1.1
###

#Get Single Store
GET http://localhost:3000/stores/5f31406deae5b044240a57c8 HTTP/1.1
###

#Get Filtered Stores
GET http://localhost:3000/stores/filteredStores/Meat HTTP/1.1
content-type: application/json
###

#Get Stores By Location /:min_lat/:max_lat/:min_lng/:max_lng
GET http://localhost:3000/stores/getStoresByLocation/48.03588261127108/48.321587137220874/11.319360693940175/11.88165927792455 HTTP/1.1
content-type: application/json
###

#Add Review
POST http://localhost:3000/stores/addReview/5f31406deae5b044240a57c8 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzNjMDEyZDRlZmY3MWIzY2ZhNmE1ZCIsImVtYWlsIjoiVGVzdEVtYWlsMTVAd2ViLmRlIiwiaWF0IjoxNjA5MTAzMDI3LCJleHAiOjE2MDkxODk0Mjd9.JTmBmIGWOW380zzYKTNdnsjxvDIMr629EDmlrbak3HQ

{
    "rating": 5,
    "text": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
}
###

#Edit Review
POST http://localhost:3000/stores/editReview/5f31406deae5b044240a57c8/20 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzNjMDEyZDRlZmY3MWIzY2ZhNmE1ZCIsImVtYWlsIjoiVGVzdEVtYWlsMTVAd2ViLmRlIiwiaWF0IjoxNjA5MTA3MzI0LCJleHAiOjE2MDkxOTM3MjR9.cr659oIWDVn2B1FyEhgWvx806e-yxRixM06FaVE87Jo

{   
    "rating": 4,
    "text": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
}
###

#Delete Review
DELETE http://localhost:3000/stores/deleteReview/5f31406deae5b044240a57c8/17 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzNjMDEyZDRlZmY3MWIzY2ZhNmE1ZCIsImVtYWlsIjoiVGVzdEVtYWlsMTVAd2ViLmRlIiwiaWF0IjoxNjA5MTA3MzI0LCJleHAiOjE2MDkxOTM3MjR9.cr659oIWDVn2B1FyEhgWvx806e-yxRixM06FaVE87Jo

###

#Create Store
POST http://localhost:3000/stores/createStore HTTP/1.1
content-type: application/json

{
    "userEmail": "TestEmail15@web.de",
    "title": "Test Store 4",
    "subtitle": "",
    "description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam.",
    "tags": ["meat", "steak", "cow", "beer"],
    "images": [
        {
            "id": "0",
            "src": "https://www.peta.de/mediadb/cache/1800x1200/kuh-claudio-schwarz-purzlbaum-uR5w1Y9-8yE-unsplash.jpg",
            "title": "cow"
        },
        {   
            "id": "1",
            "src":"https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTeVo04Xgsk_YB77MpuYU2jA3MRZ13TNP4IMWh0LiGMaGrUG5LLXSiH1K1ywA&usqp=CAc",
            "title": "meat"
        }
    ],
    "address": {
        "postcode": "80689",
        "city": "München",
        "addressLine1": "Fischer-von-Erlach-Straße 9",
        "country": "Germany"
    },
    "mapIcon": "fish",
    "lat": "48.139911",
    "lng": "11.480547"
}
###

#Delete Store
DELETE http://localhost:3000/stores/deleteStore/5fc41998982b4a2eb89214d5 HTTP/1.1
content-type: application/json
###

#Add Product
POST http://localhost:3000/stores/addProduct/5f31406deae5b044240a57c8 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzNjMDEyZDRlZmY3MWIzY2ZhNmE1ZCIsImVtYWlsIjoiVGVzdEVtYWlsMTVAd2ViLmRlIiwiaWF0IjoxNjA5MTA3MzI0LCJleHAiOjE2MDkxOTM3MjR9.cr659oIWDVn2B1FyEhgWvx806e-yxRixM06FaVE87Jo

{
    "storeId": "5f31406deae5b044240a57c8",
    "title": "Product 2",
    "description": "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
    "imgSrc": "http://t2.gstatic.com/images?q=tbn:ANd9GcSBt4zB0dG24tS2BYvgTESt9nMTmIgYcKqQjO3KBHXgbjwNuipSgSaFecgStaLb-l6hqwOTC1gceewd5SitD24",
    "price": "20.00",
    "currency": "EUR",
    "currencySymbol": "€",
    "quantityType": "Kilograms",
    "quantityValue": "1",
    "stockAmount": 1
}
###

#Delete Product
DELETE http://localhost:3000/stores/deleteProduct/5f31406deae5b044240a57c8/15 HTTP/1.1
content-type: application/json
###

#Add Product
POST http://localhost:3000/stores/getFilteredStores2 HTTP/1.1
content-type: application/json

{
    "tags": []
    //"filterArray": [["tags","beer"], ["tags", "meat"]]
}
###

#Update Product
POST http://localhost:3000/stores/editProduct/5f31406deae5b044240a57c8/11 HTTP/1.1
content-type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYzNjMDEyZDRlZmY3MWIzY2ZhNmE1ZCIsImVtYWlsIjoiVGVzdEVtYWlsMTVAd2ViLmRlIiwiaWF0IjoxNjA5MTA3MzI0LCJleHAiOjE2MDkxOTM3MjR9.cr659oIWDVn2B1FyEhgWvx806e-yxRixM06FaVE87Jo

{
    "storeId": "5f31406deae5b044240a57c8",
    "productId": "11",
    "title": "Test4",
    "description":"Test2Test2Test2Test2Test2Test2" ,
    "imgSrc": "https://upload.wikimedia.org/wikipedia/commons/9/9a/Gull_portrait_ca_usa.jpg",
    "price":"1.00",
    "datetime": "12-10-2020, 16:53",
    "quantityType": "Kilograms",
    "quantityValue": "1",
    "currency": "EUR",
    "currencySymbol": "€",
    "stockAmount": 1
}
###

#Update Stock Amount
PATCH http://localhost:3000/stores/updateStockAmount/5f31406deae5b044240a57c8/15 HTTP/1.1
content-type: application/json

{
    //"storeId": "5f31406deae5b044240a57c8",
    //"productId": "11",
    "stockAmount": 6
}
###

#Geo Code Test "address": "Magdalena-Herrle-Straße 15, 85051 Ingolstadt, Deutschland",
POST http://localhost:3000/stores/geoCodeTest HTTP/1.1
content-type: application/json

{
    //"zipcode": "85051",
    //"city": "Ingolstadt",
    //"streetName": "Magdalena-Herrle-Straße",
    //"streetNumber": "15",
    //"country": "Germany"
    "address": "Münchener Str. 7, 85748 Garching, Deutschland"

}
###