@baseUrl = http://localhost:3000
@userEmail = TestEmail4@web.de
@userPassword = TestPassword1!
@userFirstName = firstName
@userLastName = lastName
@userPhoneNumber = 0001 123456789
@userBirthdate = 29.11.2020
@userCity = TestCity
@userPostcode = 00001
@userAddressLine1 = TestStreet 1
@space = {{$dotenv %space}}

# Get All Users
GET {{baseUrl}}/users HTTP/1.1
###

##################################################
# Register User
##################################################
# @name authRegisterUser
POST {{baseUrl}}/auth/register-user HTTP/1.1
content-type: application/json

{
    "email": "{{userEmail}}",
    "password": "{{userPassword}}",
    "firstName": "{{userFirstName}}",
    "lastName": "{{userLastName}}",
    "phoneNumber": "{{userPhoneNumber}}",
    "birthdate": "{{userBirthdate}}",
    "city": "{{userCity}}",
    "postcode": "{{userPostcode}}",
    "addressLine1": "{{userAddressLine1}}"
}
###

##################################################
# Verify User
##################################################
# @name authVerifyEmail
@verificationToken = 38231f85ebcca2619a9a0c88113da66239b002a9445d9916a7320b6468fcc25e39e3059e011623e1
POST {{baseUrl}}/auth/verify-registration/{{verificationToken}} HTTP/1.1
content-type: application/json

{}
###
@accessToken = {{authVerifyEmail.response.body.authToken}}

##################################################
# Login User
##################################################
# @name authLoginUser
POST {{baseUrl}}/auth/login-user HTTP/1.1
content-type: application/json

{
    "email": "TestEmail4@web.de",
    "password": "TestPassword1!"
}
###
@accessToken = {{authLoginUser.response.body.authToken}}

##################################################
# Get single User
##################################################
# @name getSingleUser
GET {{baseUrl}}/users HTTP/1.1
x-access-token: {{accessToken}}
###

##################################################
# PW Reset - Send E-Mail
##################################################
# @name pwResetSendEmail
POST {{baseUrl}}/auth/send-password-reset-mail HTTP/1.1
content-type: application/json

{
    "email": "{{userEmail}}",
    "birthdate": "{{userBirthdate}}"
}
###
@pwResetToken = 020a3d70de48ec543adc357701e9015c6f62116ea1a3dbfcde786251142c6498d3b8260488413093

##################################################
# PW Reset - Check reset token
##################################################
# @name pwResetCheckResetToken
GET {{baseUrl}}/auth/check-reset-token/{{pwResetToken}} HTTP/1.1
###

##################################################
# PW Reset - Reset password
##################################################
# @name pwResetResetPassword
POST {{baseUrl}}/auth/reset-password/{{pwResetToken}} HTTP/1.1
content-type: application/json

{
    "password": "Test1!---"
}
###

# Send Test Mail
POST {{baseUrl}}/users/sendTestMail HTTP/1.1
content-type: application/json

{
    "contentType": "testMail",
    "mailAddress": "rkerscher@gmx.de"
}
###


# Testing Endpoint
POST {{baseUrl}}/users/user-testing HTTP/1.1
content-type: application/json

{
    "id": "6042541b40aa5c7b38dc3806",
    "email": "TestEmail6@web.de",
    "user": {
        "email": "TestEmail6@web.de"
    }
}
###